"""Initial database schema

Revision ID: 4a6de5a6c769
Revises: 
Create Date: 2025-08-07 01:42:39.569360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a6de5a6c769'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('max_context_tokens', sa.Integer(), nullable=True),
    sa.Column('importance_threshold', sa.Float(), nullable=True),
    sa.Column('compression_algorithm', sa.String(length=50), nullable=True),
    sa.Column('archival_threshold_days', sa.Integer(), nullable=True),
    sa.Column('auto_cleanup_enabled', sa.Boolean(), nullable=True),
    sa.Column('max_conversation_memories', sa.Integer(), nullable=True),
    sa.Column('semantic_similarity_threshold', sa.Float(), nullable=True),
    sa.Column('memory_decay_factor', sa.Float(), nullable=True),
    sa.Column('policy_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('applies_to_user_tier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_name')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('credits_remaining', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_user_profiles_role'), 'user_profiles', ['role'], unique=False)
    op.create_table('clones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('expertise_areas', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('communication_style', sa.JSON(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clones_category'), 'clones', ['category'], unique=False)
    op.create_index('ix_clones_category_published', 'clones', ['category', 'is_published'], unique=False)
    op.create_index('ix_clones_creator_active', 'clones', ['creator_id', 'is_active'], unique=False)
    op.create_table('memory_usage_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_memories_stored', sa.Integer(), nullable=True),
    sa.Column('context_retrievals', sa.Integer(), nullable=True),
    sa.Column('memory_searches_performed', sa.Integer(), nullable=True),
    sa.Column('average_retrieval_time_ms', sa.Float(), nullable=True),
    sa.Column('total_memory_size_kb', sa.Float(), nullable=True),
    sa.Column('compressed_memories_count', sa.Integer(), nullable=True),
    sa.Column('archived_memories_count', sa.Integer(), nullable=True),
    sa.Column('memory_hit_rate', sa.Float(), nullable=True),
    sa.Column('context_relevance_score', sa.Float(), nullable=True),
    sa.Column('user_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_memory_usage_stats_date')
    )
    op.create_index('ix_memory_usage_stats_user_date', 'memory_usage_stats', ['user_id', 'date'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_user_token', 'refresh_tokens', ['user_id', 'token_hash'], unique=False)
    op.create_table('summary_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=20), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('output_format', sa.JSON(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('include_insights', sa.Boolean(), nullable=True),
    sa.Column('include_action_items', sa.Boolean(), nullable=True),
    sa.Column('include_recommendations', sa.Boolean(), nullable=True),
    sa.Column('include_emotional_analysis', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_summary_templates_public', 'summary_templates', ['is_public'], unique=False)
    op.create_index('ix_summary_templates_type', 'summary_templates', ['template_type'], unique=False)
    op.create_table('user_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('documents_uploaded', sa.Integer(), nullable=True),
    sa.Column('knowledge_entries_added', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_analytics_date')
    )
    op.create_index('ix_user_analytics_user_date', 'user_analytics', ['user_id', 'date'], unique=False)
    op.create_table('user_memory_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('key_preferences', sa.JSON(), nullable=True),
    sa.Column('communication_patterns', sa.JSON(), nullable=True),
    sa.Column('topics_of_interest', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('personality_insights', sa.JSON(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('context_version', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_memory_contexts_user_updated', 'user_memory_contexts', ['user_id', 'updated_at'], unique=False)
    op.create_table('bulk_summarization_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('session_filters', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('summary_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('processed_sessions', sa.Integer(), nullable=True),
    sa.Column('failed_sessions', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_format', sa.String(length=20), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['summary_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bulk_jobs_created', 'bulk_summarization_jobs', ['created_at'], unique=False)
    op.create_index('ix_bulk_jobs_user_status', 'bulk_summarization_jobs', ['user_id', 'status'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clone_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clone_id'], ['clones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_sessions_updated', 'chat_sessions', ['updated_at'], unique=False)
    op.create_index('ix_chat_sessions_user_clone', 'chat_sessions', ['user_id', 'clone_id'], unique=False)
    op.create_table('clone_learning',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clone_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('learned_preferences', sa.JSON(), nullable=True),
    sa.Column('successful_patterns', sa.JSON(), nullable=True),
    sa.Column('adaptive_traits', sa.JSON(), nullable=True),
    sa.Column('communication_adjustments', sa.JSON(), nullable=True),
    sa.Column('learning_confidence', sa.Float(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('last_feedback_rating', sa.Float(), nullable=True),
    sa.Column('custom_system_prompt_additions', sa.Text(), nullable=True),
    sa.Column('personality_adjustments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_learning_event', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clone_id'], ['clones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clone_id', 'user_id', name='uq_clone_learning_pair')
    )
    op.create_index('ix_clone_learning_clone_user', 'clone_learning', ['clone_id', 'user_id'], unique=False)
    op.create_table('creator_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('clone_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.Column('sessions_count', sa.Integer(), nullable=True),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('ratings_count', sa.Integer(), nullable=True),
    sa.Column('user_retention_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clone_id'], ['clones.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_creator_analytics_clone_date', 'creator_analytics', ['clone_id', 'date'], unique=False)
    op.create_index('ix_creator_analytics_creator_date', 'creator_analytics', ['creator_id', 'date'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clone_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clone_id'], ['clones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_clone_status', 'documents', ['clone_id', 'processing_status'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clone_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clone_id'], ['clones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_entries_clone_category', 'knowledge_entries', ['clone_id', 'category'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clone_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('demo_mode', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('rate_per_minute', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clone_id'], ['clones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_clone_status', 'sessions', ['clone_id', 'status'], unique=False)
    op.create_index('ix_sessions_user_status', 'sessions', ['user_id', 'status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_sender_type', 'chat_messages', ['sender_type'], unique=False)
    op.create_index('ix_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('conversation_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clone_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('memory_summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('emotional_context', sa.JSON(), nullable=True),
    sa.Column('topics_discussed', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('relevance_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('memory_type', sa.String(length=20), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clone_id'], ['clones.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_memories_importance', 'conversation_memories', ['importance_score'], unique=False)
    op.create_index('ix_conversation_memories_topics', 'conversation_memories', ['topics_discussed'], unique=False)
    op.create_index('ix_conversation_memories_user_clone', 'conversation_memories', ['user_id', 'clone_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk_index')
    )
    op.create_index('ix_document_chunks_document_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('context_used', sa.Text(), nullable=True),
    sa.Column('cost_increment', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_table('session_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('key_insights', sa.JSON(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('next_session_topics', sa.JSON(), nullable=True),
    sa.Column('emotional_tone', sa.String(length=50), nullable=True),
    sa.Column('main_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('user_satisfaction_indicators', sa.JSON(), nullable=True),
    sa.Column('learning_outcomes', sa.JSON(), nullable=True),
    sa.Column('conversation_quality_score', sa.Float(), nullable=True),
    sa.Column('summary_type', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['summary_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_summaries_generated', 'session_summaries', ['generated_at'], unique=False)
    op.create_index('ix_session_summaries_session_type', 'session_summaries', ['session_id', 'summary_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_summaries_session_type', table_name='session_summaries')
    op.drop_index('ix_session_summaries_generated', table_name='session_summaries')
    op.drop_table('session_summaries')
    op.drop_index('ix_messages_session_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_document_chunks_document_index', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_conversation_memories_user_clone', table_name='conversation_memories')
    op.drop_index('ix_conversation_memories_topics', table_name='conversation_memories')
    op.drop_index('ix_conversation_memories_importance', table_name='conversation_memories')
    op.drop_table('conversation_memories')
    op.drop_index('ix_chat_messages_session_created', table_name='chat_messages')
    op.drop_index('ix_chat_messages_sender_type', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_sessions_user_status', table_name='sessions')
    op.drop_index('ix_sessions_clone_status', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_knowledge_entries_clone_category', table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index('ix_documents_clone_status', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_creator_analytics_creator_date', table_name='creator_analytics')
    op.drop_index('ix_creator_analytics_clone_date', table_name='creator_analytics')
    op.drop_table('creator_analytics')
    op.drop_index('ix_clone_learning_clone_user', table_name='clone_learning')
    op.drop_table('clone_learning')
    op.drop_index('ix_chat_sessions_user_clone', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_updated', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_bulk_jobs_user_status', table_name='bulk_summarization_jobs')
    op.drop_index('ix_bulk_jobs_created', table_name='bulk_summarization_jobs')
    op.drop_table('bulk_summarization_jobs')
    op.drop_index('ix_user_memory_contexts_user_updated', table_name='user_memory_contexts')
    op.drop_table('user_memory_contexts')
    op.drop_index('ix_user_analytics_user_date', table_name='user_analytics')
    op.drop_table('user_analytics')
    op.drop_index('ix_summary_templates_type', table_name='summary_templates')
    op.drop_index('ix_summary_templates_public', table_name='summary_templates')
    op.drop_table('summary_templates')
    op.drop_index('ix_refresh_tokens_user_token', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_memory_usage_stats_user_date', table_name='memory_usage_stats')
    op.drop_table('memory_usage_stats')
    op.drop_index('ix_clones_creator_active', table_name='clones')
    op.drop_index('ix_clones_category_published', table_name='clones')
    op.drop_index(op.f('ix_clones_category'), table_name='clones')
    op.drop_table('clones')
    op.drop_index(op.f('ix_user_profiles_role'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('memory_policies')
    # ### end Alembic commands ###